module.exports = {
    name: 'pasta',
    description: "this is a ping command!",
    execute(message, args){
        
        const pasta = [ 
        "Spaghettoni",
        "Spaghetti",
        "Spaghettini",
        "Fedelini",
        "Vermicelloni",
        "Vermicelli",
        "Capellini",
        "Capelli d'angelo",
        "Barbina",
        "Bucatini",
        "Perciatelli",
        "Fusilli lunghi",
        "Fusilli bucati",
        "Pici",
        "Soba - そば (Japanese)",
        "Udon - うどん (Japanese)",
        "Cu mian - 粗麵 (Chinese)",
        "Ziti",
        "Zitoni",
        "Spaghetti alla chitarra",
        "Ciriole",
        "Bavette",
        "Bavettine",
        "Fettuce",
        "Fettuccine",
        "Fettucelle",
        "Lagane",
        "Lasagne",
        "Lasagnette",
        "Lasagnotte",
        "Linguettine",
        "Linguine",
        "Mafalde",
        "Mafaldine",
        "Pappardelle",
        "Pillus",
        "Pizzoccheri",
        "Sagnarelli",
        "Scialatelli or scilatielli",
        "Stringozzi",
        "Tagliatelle",
        "Taglierini",
        "Trenette",
        "Tripoline",
        "Shahe fen -(Chinese)",
        "Biáng biáng noodles - Chinese)",
        "Calamarata",
        "Calamaretti",
        "Cannelloni",
        "Cavatappi",
        "Cellentani",
        "Chifferi",
        "Ditalini",
        "Fideuà",
        "Gomito",
        "Elicoidali",
        "Fagioloni",
        "Fusilli",
        "Garganelli",
        "Gemelli",
        "Maccheroncelli",
        "Maltagliati",
        "Manicotti",
        "Marziani",
        "Mezzani pasta",
        "Mezze penne",
        "Mezzi bombardoni",
        "Mostaccioli",
        "Paccheri",
        "Pasta al ceppo",
        "Penne",
        "Penne rigate",
        "Penne lisce",
        "Penne zita",
        "Pennette",
        "Pennoni",
        "Rigatoncini",
        "Rigatoni",
        "Sagne 'ncannulate",
        "Spirali",
        "Spiralini",
        "Trenne",
        "Trennette",
        "Tortiglioni",
        "Tuffol",
        "Croxetti",
        "Farfalle",
        "Farfalloni",
        "Fiorentine",
        "Fiori",
        "Foglie d'ulivo",
        "Gigli",
        "Gramigna",
        "Lanterne",
        "Lumache",
        "Lumaconi",
        "Maltagliati",
        "Mandala",
        "Marille",
        "Orecchiette",
        "Pipe",
        "Quadrefiore",
        "Radiatori",
        "Ricciolini",
        "Ricciutelle",
        "Rotelle",
        "Rotini",
        "Strozzapreti",
        "Torchio",
        "Trofie",
        "Gnocchi",
        "Passatelli",
        "Spätzle",
        "Agnolotti",
        "Cannelloni",
        "Casoncelli or casonsèi",
        "Casunziei",
        "Fagottini",
        "Maultasche",
        "Mezzelune",
        "Occhi di lupo",
        "Pelmeni",
        "Pierogi",
        "Ravioli",
        "Sacchettini",
        "Sacchettoni",
        "Tortellini",
        "Tortelloni",
        "Acini di pepe",
        "Bead-like pasta",
        "Alfabeto",
        "Anelli",
        "Anellini",
        "Couscous",
        "Conchigliette",
        "Corallini",
        "Ditali",
        "Ditalini",
        "Egg barley",
        "Farfalline",
        "Fideos",
        "Filini",
        "Fregula",
        "Funghini",
        "Israeli couscous",
        "Occhi di pernice",
        "Orzo (also, risoni)",
        "Pastina",
        "Pearl Pasta",
        "Ptitim",
        "Quadrettini",
        "Risi",
        "Seme di melone",
        "Stelle",
        "Stelline",
        "Stortini",
        "Tarhana"
     ]
        
        const result = pasta[Math.floor(Math.random() * 166)]    
        
        
        message.channel.send(result);
    }
}